# Setup
title:               Joey's blog
tagline:             'A blog with Jekyll theme'
description:         'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 https://oliverxuzy.github.io/blog/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             zxu68341@icloud.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15

# collections:
collections:
  tutorials:
    output: true
    permalink: /:collection/:path/ # used for access on http://localhost:4000/tutorials/highDimStat/
    
